import type { NewsPost, Comment, GeneralPost } from "@/types/post"
import type { MonthSchedule, Availability } from "@/types/schedule"
import type { Event } from "@/types/event"
import type { Meeting } from "@/types/meeting"

// Mock authors
const owners = [
  {
    id: "owner1",
    name: "Thomas Schmidt",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: true,
  },
  {
    id: "owner2",
    name: "Laura Müller",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: true,
  },
]

const staff = [
  {
    id: "staff1",
    name: "Max Mustermann",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: false,
  },
  {
    id: "staff2",
    name: "Anna Weber",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: false,
  },
  {
    id: "staff3",
    name: "Jan Becker",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: false,
  },
  {
    id: "staff4",
    name: "Lisa Schneider",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: false,
  },
  {
    id: "staff5",
    name: "Tim Hoffmann",
    profileImage: "/placeholder.svg?height=40&width=40",
    isOwner: false,
  },
]

// Mock comments
const mockComments: Comment[] = [
  {
    id: "comment1",
    content: "Super, danke für die Info!",
    author: staff[0],
    createdAt: "2023-06-15T14:30:00Z",
  },
  {
    id: "comment2",
    content: "Ich freue mich schon auf das Event!",
    author: staff[1],
    createdAt: "2023-06-15T15:45:00Z",
  },
  {
    id: "comment3",
    content: "Kann leider nicht dabei sein, bin im Urlaub.",
    author: staff[2],
    createdAt: "2023-06-16T09:20:00Z",
  },
  {
    id: "comment4",
    content: "Danke für die Erinnerung!",
    author: staff[0],
    createdAt: "2023-06-16T10:15:00Z",
  },
  {
    id: "comment5",
    content: "Ich habe noch eine Frage dazu. Können wir das morgen besprechen?",
    author: staff[1],
    createdAt: "2023-06-16T11:30:00Z",
    mediaUrl: "/placeholder.svg?height=200&width=300",
  },
]

// Mock news posts
export const mockNewsPosts: NewsPost[] = [
  {
    id: "post1",
    title: "Wichtige Änderungen im Dienstplan",
    content:
      "Liebe Mitarbeiter, ab nächster Woche gibt es einige Änderungen im Dienstplan. Bitte schaut euch die neuen Zeiten an und gebt Bescheid, falls es Probleme gibt. Wir müssen die Besetzung an der Bar verstärken, daher werden einige von euch umgeteilt. Danke für euer Verständnis!",
    author: owners[0],
    createdAt: "2023-06-15T12:00:00Z",
    important: true,
    pinned: true,
    categories: ["Dienstplan", "Wichtig"],
    commentCount: 3,
    comments: [mockComments[0], mockComments[1], mockComments[2]],
    hasVoting: false,
    archived: false,
  },
  {
    id: "post2",
    title: "Neues Event am 25. Juli",
    content:
      "Wir haben ein neues Event für den 25. Juli geplant. Es wird ein Special Guest DJ kommen, daher erwarten wir viele Gäste. Alle Infos findet ihr im Anhang. Bitte teilt das Event in euren sozialen Medien!",
    author: owners[1],
    createdAt: "2023-06-14T09:30:00Z",
    important: false,
    pinned: false,
    categories: ["Event", "Ankündigung"],
    mediaUrl: "/placeholder.svg?height=400&width=600",
    commentCount: 2,
    comments: [mockComments[3], mockComments[4]],
    hasVoting: false,
    archived: false,
  },
  {
    id: "post3",
    title: "Abstimmung: Weihnachtsfeier Termin",
    content:
      "Wir planen unsere jährliche Weihnachtsfeier und möchten wissen, welcher Termin für die meisten von euch passt. Bitte stimmt ab!",
    author: owners[0],
    createdAt: "2023-06-10T15:45:00Z",
    important: false,
    pinned: false,
    categories: ["Team", "Abstimmung"],
    commentCount: 0,
    hasVoting: true,
    voting: {
      question: "Welcher Termin passt dir am besten für die Weihnachtsfeier?",
      options: [
        { id: "option1", text: "15. Dezember", count: 3 },
        { id: "option2", text: "22. Dezember", count: 5 },
        { id: "option3", text: "5. Januar", count: 2 },
      ],
      isEnded: false,
      totalVotes: 10,
    },
    archived: false,
  },
  {
    id: "post4",
    title: "Neue Getränkekarte ab September",
    content:
      "Ab September werden wir eine neue Getränkekarte einführen. Es gibt einige neue Cocktails und Spezialitäten. Alle Mitarbeiter bekommen eine Schulung zu den neuen Getränken. Die Termine dafür werden noch bekannt gegeben.",
    author: owners[1],
    createdAt: "2023-06-05T11:20:00Z",
    important: true,
    pinned: false,
    categories: ["Ankündigung", "Schulung"],
    commentCount: 0,
    hasVoting: false,
    archived: false,
  },
  {
    id: "post5",
    title: "Feedback zur letzten Veranstaltung",
    content:
      "Vielen Dank an alle, die am letzten Wochenende gearbeitet haben. Die Veranstaltung war ein großer Erfolg! Wir haben viel positives Feedback von den Gästen bekommen. Besonders die neue Lichtanlage kam gut an.",
    author: owners[0],
    createdAt: "2023-06-01T16:30:00Z",
    important: false,
    pinned: false,
    categories: ["Feedback"],
    commentCount: 0,
    hasVoting: false,
    archived: false,
  },
]

// Mock general posts
export const mockGeneralPosts: GeneralPost[] = [
  {
    id: "general1",
    content: "Hat jemand Lust, nach der Schicht noch etwas trinken zu gehen?",
    author: staff[0],
    createdAt: "2023-06-16T18:30:00Z",
    categories: ["Freizeit"],
    commentCount: 2,
    comments: [
      {
        id: "gcomment1",
        content: "Ich bin dabei!",
        author: staff[1],
        createdAt: "2023-06-16T18:35:00Z",
      },
      {
        id: "gcomment2",
        content: "Ich kann leider nicht, muss morgen früh raus.",
        author: staff[2],
        createdAt: "2023-06-16T18:40:00Z",
      },
    ],
    reactions: {
      "👍": 3,
      "❤️": 1,
    },
    archived: false,
  },
  {
    id: "general2",
    content: "Kann jemand meinen Dienst am Samstag übernehmen? Ich habe einen wichtigen Termin bekommen.",
    author: staff[1],
    createdAt: "2023-06-15T10:15:00Z",
    categories: ["Dienstwechsel", "Anfrage"],
    commentCount: 1,
    comments: [
      {
        id: "gcomment3",
        content: "Ich kann übernehmen, wenn du dafür meinen Dienst am Sonntag übernimmst.",
        author: staff[2],
        createdAt: "2023-06-15T10:30:00Z",
      },
    ],
    reactions: {
      "👍": 1,
      "😢": 2,
    },
    archived: false,
  },
  {
    id: "general3",
    content: "Hat jemand Erfahrung mit dem neuen Kassensystem? Ich komme mit der Abrechnung nicht klar.",
    author: staff[2],
    createdAt: "2023-06-14T14:20:00Z",
    categories: ["Frage", "Hilfe"],
    commentCount: 2,
    comments: [
      {
        id: "gcomment4",
        content: "Ich kann dir helfen, bin morgen ab 16 Uhr da.",
        author: staff[0],
        createdAt: "2023-06-14T14:30:00Z",
      },
      {
        id: "gcomment5",
        content: "Es gibt auch eine Anleitung im Büro, die ist ganz hilfreich.",
        author: owners[1],
        createdAt: "2023-06-14T15:00:00Z",
      },
    ],
    reactions: {
      "👍": 2,
      "❤️": 1,
    },
    archived: false,
  },
  {
    id: "general4",
    content: "Schaut mal, was für ein tolles Foto vom letzten Event! War ein super Abend mit euch allen.",
    author: staff[0],
    createdAt: "2023-06-12T09:45:00Z",
    categories: ["Foto", "Event"],
    mediaUrl: "/placeholder.svg?height=400&width=600",
    commentCount: 3,
    reactions: {
      "👍": 5,
      "❤️": 3,
      "😂": 1,
    },
    archived: false,
  },
  {
    id: "general5",
    content: "Weiß jemand, wo der Schlüssel für den Lagerraum ist? Ich kann ihn nirgends finden.",
    author: staff[1],
    createdAt: "2023-06-10T16:30:00Z",
    categories: ["Frage"],
    commentCount: 1,
    comments: [
      {
        id: "gcomment6",
        content: "Der liegt im Büro auf dem Schreibtisch, hab ihn gerade gesehen.",
        author: staff[2],
        createdAt: "2023-06-10T16:35:00Z",
      },
    ],
    reactions: {
      "👍": 1,
    },
    archived: false,
  },
]

// Mock events
export const mockEvents: Event[] = [
  {
    id: "event1",
    name: "Techno Night mit DJ Spark",
    date: "2023-07-25",
    startTime: "22:00",
    endTime: "05:00",
    description:
      "Eine Nacht voller elektronischer Beats und treibender Rhythmen. DJ Spark wird euch mit seinem einzigartigen Sound begeistern.",
    location: "Alte Zimmerei, Hauptsaal",
    imageUrl: "/placeholder.svg?height=600&width=800",
    flyerUrl: "/placeholder.svg?height=800&width=600",
    djs: [
      {
        id: "dj1",
        name: "DJ Spark",
        startTime: "00:00",
        endTime: "03:00",
        notes: "Hauptact",
      },
      {
        id: "dj2",
        name: "DJ Luna",
        startTime: "22:00",
        endTime: "00:00",
        notes: "Warm-up",
      },
      {
        id: "dj3",
        name: "DJ Beat",
        startTime: "03:00",
        endTime: "05:00",
        notes: "Closing",
      },
    ],
    shifts: [
      {
        id: "shift1",
        date: "2023-07-25",
        startTime: "21:00",
        endTime: "02:00",
        type: "Kasse",
        staff: staff[0],
      },
      {
        id: "shift2",
        date: "2023-07-25",
        startTime: "21:00",
        endTime: "02:00",
        type: "Garderobe",
        staff: staff[1],
      },
      {
        id: "shift3",
        date: "2023-07-25",
        startTime: "02:00",
        endTime: "05:30",
        type: "Garderobe",
        staff: staff[2],
      },
      {
        id: "shift4",
        date: "2023-07-25",
        startTime: "21:00",
        endTime: "02:00",
        type: "Bar",
        staff: staff[3],
      },
      {
        id: "shift5",
        date: "2023-07-25",
        startTime: "02:00",
        endTime: "05:30",
        type: "Bar",
        staff: staff[4],
      },
      {
        id: "shift6",
        date: "2023-07-25",
        startTime: "21:00",
        endTime: "05:30",
        type: "Security",
        staff: null,
      },
    ],
    tickets: {
      friendPlus: true,
      friends: true,
    },
    status: "upcoming",
    createdBy: owners[0],
  },
  {
    id: "event2",
    name: "Hip Hop Jam",
    date: "2023-08-05",
    startTime: "21:00",
    endTime: "04:00",
    description: "Die beste Hip Hop Party der Stadt! Mit Live-Acts und den besten DJs der Szene.",
    location: "Alte Zimmerei, Hauptsaal",
    imageUrl: "/placeholder.svg?height=600&width=800",
    flyerUrl: "/placeholder.svg?height=800&width=600",
    djs: [
      {
        id: "dj4",
        name: "DJ Scratch",
        startTime: "21:00",
        endTime: "23:00",
        notes: "Warm-up",
      },
      {
        id: "dj5",
        name: "MC Flow",
        startTime: "23:00",
        endTime: "01:00",
        notes: "Live-Act",
      },
      {
        id: "dj6",
        name: "DJ Beats",
        startTime: "01:00",
        endTime: "04:00",
        notes: "Main & Closing",
      },
    ],
    shifts: [
      {
        id: "shift7",
        date: "2023-08-05",
        startTime: "20:00",
        endTime: "01:00",
        type: "Kasse",
        staff: staff[2],
      },
      {
        id: "shift8",
        date: "2023-08-05",
        startTime: "20:00",
        endTime: "01:00",
        type: "Garderobe",
        staff: staff[3],
      },
      {
        id: "shift9",
        date: "2023-08-05",
        startTime: "01:00",
        endTime: "04:30",
        type: "Garderobe",
        staff: staff[4],
      },
      {
        id: "shift10",
        date: "2023-08-05",
        startTime: "20:00",
        endTime: "01:00",
        type: "Bar",
        staff: staff[0],
      },
      {
        id: "shift11",
        date: "2023-08-05",
        startTime: "01:00",
        endTime: "04:30",
        type: "Bar",
        staff: staff[1],
      },
    ],
    tickets: {
      friendPlus: true,
      friends: true,
    },
    status: "upcoming",
    createdBy: owners[1],
  },
  {
    id: "event3",
    name: "80er Jahre Party",
    date: "2023-08-12",
    startTime: "21:00",
    endTime: "03:00",
    description: "Tauche ein in die Welt der 80er Jahre! Mit den besten Hits aus dieser unvergesslichen Ära.",
    location: "Alte Zimmerei, Hauptsaal",
    imageUrl: "/placeholder.svg?height=600&width=800",
    flyerUrl: "/placeholder.svg?height=800&width=600",
    djs: [
      {
        id: "dj7",
        name: "DJ Retro",
        startTime: "21:00",
        endTime: "03:00",
        notes: "All night long",
      },
    ],
    shifts: [
      {
        id: "shift12",
        date: "2023-08-12",
        startTime: "20:00",
        endTime: "03:30",
        type: "Kasse",
        staff: staff[4],
      },
      {
        id: "shift13",
        date: "2023-08-12",
        startTime: "20:00",
        endTime: "03:30",
        type: "Garderobe",
        staff: staff[0],
      },
      {
        id: "shift14",
        date: "2023-08-12",
        startTime: "20:00",
        endTime: "03:30",
        type: "Bar",
        staff: staff[1],
      },
      {
        id: "shift15",
        date: "2023-08-12",
        startTime: "20:00",
        endTime: "03:30",
        type: "Bar",
        staff: null,
      },
    ],
    tickets: {
      friendPlus: false,
      friends: true,
    },
    status: "upcoming",
    createdBy: owners[0],
  },
  {
    id: "event4",
    name: "Sommerfest",
    date: "2023-07-15",
    startTime: "16:00",
    endTime: "23:00",
    description: "Unser jährliches Sommerfest mit Grillen, Drinks und guter Musik im Garten der Alten Zimmerei.",
    location: "Alte Zimmerei, Garten",
    imageUrl: "/placeholder.svg?height=600&width=800",
    flyerUrl: "/placeholder.svg?height=800&width=600",
    djs: [
      {
        id: "dj8",
        name: "DJ Sunshine",
        startTime: "16:00",
        endTime: "20:00",
        notes: "Chill-out",
      },
      {
        id: "dj9",
        name: "DJ Groove",
        startTime: "20:00",
        endTime: "23:00",
        notes: "Party",
      },
    ],
    shifts: [
      {
        id: "shift16",
        date: "2023-07-15",
        startTime: "15:00",
        endTime: "23:30",
        type: "Bar",
        staff: staff[2],
      },
      {
        id: "shift17",
        date: "2023-07-15",
        startTime: "15:00",
        endTime: "23:30",
        type: "Bar",
        staff: staff[3],
      },
      {
        id: "shift18",
        date: "2023-07-15",
        startTime: "15:00",
        endTime: "23:30",
        type: "Grill",
        staff: staff[0],
      },
    ],
    tickets: {
      friendPlus: true,
      friends: true,
    },
    status: "past",
    createdBy: owners[1],
  },
]

// Mock schedule data
export const mockSchedule: MonthSchedule = {
  year: 2023,
  month: 6, // July (0-indexed)
  days: [
    {
      date: "2023-07-01",
      shifts: [
        {
          id: "s1",
          date: "2023-07-01",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[0],
        },
        {
          id: "s2",
          date: "2023-07-01",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[1],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-02",
      shifts: [],
      hasEvent: false,
    },
    {
      date: "2023-07-07",
      shifts: [
        {
          id: "s3",
          date: "2023-07-07",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[2],
        },
        {
          id: "s4",
          date: "2023-07-07",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[3],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-08",
      shifts: [
        {
          id: "s5",
          date: "2023-07-08",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[4],
        },
        {
          id: "s6",
          date: "2023-07-08",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[0],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-14",
      shifts: [
        {
          id: "s7",
          date: "2023-07-14",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[1],
        },
        {
          id: "s8",
          date: "2023-07-14",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[2],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-15",
      shifts: [
        {
          id: "shift16",
          date: "2023-07-15",
          startTime: "15:00",
          endTime: "23:30",
          type: "Bar",
          staff: staff[2],
        },
        {
          id: "shift17",
          date: "2023-07-15",
          startTime: "15:00",
          endTime: "23:30",
          type: "Bar",
          staff: staff[3],
        },
        {
          id: "shift18",
          date: "2023-07-15",
          startTime: "15:00",
          endTime: "23:30",
          type: "Grill",
          staff: staff[0],
        },
      ],
      hasEvent: true,
      eventId: "event4",
    },
    {
      date: "2023-07-21",
      shifts: [
        {
          id: "s9",
          date: "2023-07-21",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[3],
        },
        {
          id: "s10",
          date: "2023-07-21",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[4],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-22",
      shifts: [
        {
          id: "s11",
          date: "2023-07-22",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[0],
        },
        {
          id: "s12",
          date: "2023-07-22",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[1],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-25",
      shifts: [
        {
          id: "shift1",
          date: "2023-07-25",
          startTime: "21:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[0],
        },
        {
          id: "shift2",
          date: "2023-07-25",
          startTime: "21:00",
          endTime: "02:00",
          type: "Garderobe",
          staff: staff[1],
        },
        {
          id: "shift3",
          date: "2023-07-25",
          startTime: "02:00",
          endTime: "05:30",
          type: "Garderobe",
          staff: staff[2],
        },
        {
          id: "shift4",
          date: "2023-07-25",
          startTime: "21:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[3],
        },
        {
          id: "shift5",
          date: "2023-07-25",
          startTime: "02:00",
          endTime: "05:30",
          type: "Bar",
          staff: staff[4],
        },
        {
          id: "shift6",
          date: "2023-07-25",
          startTime: "21:00",
          endTime: "05:30",
          type: "Security",
          staff: null,
        },
      ],
      hasEvent: true,
      eventId: "event1",
    },
    {
      date: "2023-07-28",
      shifts: [
        {
          id: "s13",
          date: "2023-07-28",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[2],
        },
        {
          id: "s14",
          date: "2023-07-28",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[3],
        },
      ],
      hasEvent: false,
    },
    {
      date: "2023-07-29",
      shifts: [
        {
          id: "s15",
          date: "2023-07-29",
          startTime: "18:00",
          endTime: "02:00",
          type: "Bar",
          staff: staff[4],
        },
        {
          id: "s16",
          date: "2023-07-29",
          startTime: "18:00",
          endTime: "02:00",
          type: "Kasse",
          staff: staff[0],
        },
      ],
      hasEvent: false,
    },
  ],
}

// Mock availability data
export const mockAvailability: Availability[] = [
  {
    id: "a1",
    userId: "staff1",
    date: "2023-07-10",
    isAvailable: false,
    reason: "Urlaub",
  },
  {
    id: "a2",
    userId: "staff1",
    date: "2023-07-11",
    isAvailable: false,
    reason: "Urlaub",
  },
  {
    id: "a3",
    userId: "staff1",
    date: "2023-07-12",
    isAvailable: false,
    reason: "Urlaub",
  },
  {
    id: "a4",
    userId: "staff2",
    date: "2023-07-20",
    isAvailable: false,
    reason: "Privater Termin",
  },
  {
    id: "a5",
    userId: "staff3",
    date: "2023-07-30",
    isAvailable: false,
    reason: "Krank",
  },
]

// Mock meetings
export const mockMeetings: Meeting[] = [
  {
    id: "meeting1",
    title: "Monatliches Team-Meeting",
    date: "2023-07-20",
    startTime: "14:00",
    endTime: "16:00",
    location: "Alte Zimmerei, Besprechungsraum",
    description:
      "Unser monatliches Team-Meeting mit Updates zu aktuellen Projekten, Feedback und Planung für kommende Events.",
    createdBy: owners[0],
    attendees: [
      { user: owners[0], status: "attending" },
      { user: owners[1], status: "attending" },
      { user: staff[0], status: "attending" },
      { user: staff[1], status: "attending" },
      { user: staff[2], status: "declined", declineReason: "Urlaub" },
      { user: staff[3], status: "pending" },
      { user: staff[4], status: "pending" },
    ],
    status: "upcoming",
    isProtocolFinalized: false,
  },
  {
    id: "meeting2",
    title: "Event-Planung: Sommerfest",
    date: "2023-07-05",
    startTime: "10:00",
    endTime: "12:00",
    location: "Alte Zimmerei, Besprechungsraum",
    description:
      "Planung unseres jährlichen Sommerfests. Wir besprechen das Konzept, die Aufgabenverteilung und das Budget.",
    createdBy: owners[1],
    attendees: [
      { user: owners[0], status: "attending" },
      { user: owners[1], status: "attending" },
      { user: staff[0], status: "attending" },
      { user: staff[1], status: "attending" },
      { user: staff[2], status: "attending" },
      { user: staff[3], status: "attending" },
      { user: staff[4], status: "declined", declineReason: "Krank" },
    ],
    protocol: [
      {
        id: "p1",
        title: "Termin",
        content: "Das Sommerfest findet am 15. Juli statt.",
        type: "info",
      },
      {
        id: "p2",
        title: "Budget",
        content: "Das Budget für das Sommerfest beträgt 2000€.",
        type: "decision",
      },
      {
        id: "p3",
        title: "Getränkekarte erstellen",
        content: "Eine spezielle Getränkekarte für das Sommerfest muss erstellt werden.",
        type: "task",
        assignedTo: staff[1],
        dueDate: "2023-07-10",
      },
      {
        id: "p4",
        title: "DJ buchen",
        content: "DJ Sunshine und DJ Groove werden für das Sommerfest gebucht.",
        type: "decision",
      },
    ],
    status: "past",
    isProtocolFinalized: true,
  },
  {
    id: "meeting3",
    title: "Schulung: Neue Getränkekarte",
    date: "2023-08-10",
    startTime: "15:00",
    endTime: "17:00",
    location: "Alte Zimmerei, Bar",
    description:
      "Schulung für alle Mitarbeiter zur neuen Getränkekarte. Wir lernen die neuen Cocktails und Spezialitäten kennen.",
    createdBy: owners[0],
    attendees: [
      { user: owners[0], status: "attending" },
      { user: owners[1], status: "attending" },
      { user: staff[0], status: "pending" },
      { user: staff[1], status: "pending" },
      { user: staff[2], status: "pending" },
      { user: staff[3], status: "pending" },
      { user: staff[4], status: "pending" },
    ],
    status: "upcoming",
    isProtocolFinalized: false,
  },
  {
    id: "meeting4",
    title: "Jahresplanung 2024",
    date: "2023-06-15",
    startTime: "09:00",
    endTime: "12:00",
    location: "Alte Zimmerei, Besprechungsraum",
    description:
      "Planung der Events und Projekte für das Jahr 2024. Wir besprechen das Budget, die Marketingstrategie und potenzielle neue Veranstaltungsformate.",
    createdBy: owners[0],
    attendees: [
      { user: owners[0], status: "attending" },
      { user: owners[1], status: "attending" },
      { user: staff[0], status: "attending" },
      { user: staff[1], status: "declined", declineReason: "Privater Termin" },
      { user: staff[2], status: "attending" },
      { user: staff[3], status: "attending" },
      { user: staff[4], status: "attending" },
    ],
    protocol: [
      {
        id: "p5",
        title: "Budget 2024",
        content: "Das Budget für Events im Jahr 2024 wurde auf 50.000€ festgelegt.",
        type: "decision",
      },
      {
        id: "p6",
        title: "Neue Veranstaltungsformate",
        content:
          "Es wurden drei neue Veranstaltungsformate vorgeschlagen: Brunch-Events, Afterwork-Partys und Themen-Wochenenden.",
        type: "info",
      },
      {
        id: "p7",
        title: "Marketing-Strategie",
        content:
          "Die Social-Media-Präsenz soll ausgebaut werden. Dafür wird ein dedizierter Social-Media-Manager eingestellt.",
        type: "decision",
      },
      {
        id: "p8",
        title: "Kooperationen",
        content: "Potenzielle Kooperationen mit lokalen Künstlern und Gastronomen sollen geprüft werden.",
        type: "task",
        assignedTo: owners[1],
        dueDate: "2023-07-31",
      },
    ],
    status: "past",
    isProtocolFinalized: true,
  },
]

